###Update:2018/01/08###
###Editor:yu-sheng##
UserParameter=fimo.megacli.dev.rotation[*],smartctl -d megaraid,$1 -a /dev/sda |grep "Rotation Rate"|grep ":"| cut -f2 -d: |tr -d " "
UserParameter=fimo.megacli.dev.sn[*],smartctl -d megaraid,$1 -a /dev/sda |grep "Serial Number:"| awk '{print $$3}'
UserParameter=fimo.megacli.dev.dm[*],smartctl -d megaraid,$1 -a /dev/sda |grep "Device Model:"| awk '{print $$3,$$4}'
UserParameter=fimo.megacli.dev.uc[*],smartctl -d megaraid,$1 -a /dev/sda |grep "User Capacity:"| sed 's/\[//g'| sed 's/\]//g'| awk '{print $$5,$$6}'

UserParameter=fimo.megacli.dev.smvalue[*],smartctl -d megaraid,$1 -a /dev/sda| egrep $2| tail -1| xargs| awk '{print $$4}'
UserParameter=fimo.megacli.dev.smraw[*],smartctl -d megaraid,$1 -a /dev/sda| egrep $2| tail -1| xargs| awk '{print $$10}'
UserParameter=fimo.megacli.dev.smartresult[*],smartctl -H -d  megaraid,$1 /dev/sda |grep "SMART"|grep ":"| cut -f2 -d: |tr -d " "
UserParameter=fimo.megacli.info.show.[*],/opt/MegaRAID/MegaCli/MegaCli64 -PDInfo -PhysDrv [$1:$2] -aAll -NoLog |grep "$3"|grep ":"| cut -f2 -d: |tr -d " "| awk -F "[" '{print $$1}'
UserParameter=get.raid.vd.getraidinfo,python /opt/FiMo3/raid_disk_storcli/nodefiles/script/ori_ldpdinfo.py
UserParameter=get.raid.vd.getpdinfo,python /opt/FiMo3/raid_disk_storcli/nodefiles/script/ori_pdinfo.py

UserParameter=fimo.raid.vd.getvdlist,python /opt/FiMo3/raid_disk_storcli/nodefiles/script/lld_vdlist.py
UserParameter=fimo.raid.vd.getvdpdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/lld_me_raid_pd_info.py
UserParameter=fimo.raid.vd.getpdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/lld_pdinfo.py

UserParameter=fimo.raid.vd.getldpdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/lld_ldpdlist.py

UserParameter=fimo.raid.vd.upadte.ldpdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/update_ldpddlist.py
UserParameter=fimo.raid.vd.upadte.pdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/update_pdinfo.py


UserParameter=fimo.device.getpdinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/trap_update_pdinfo.py $1
UserParameter=fimo.device.getldinfo[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/trap_update_ldinfo.py $1



UserParameter=fimo.device.id[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/trap_update_ldpddlist.py $1 $2




