# Local
UserParameter=raid.arcconf[*],python /opt/FiMo3/raid_disk_storcli/nodefiles/script/raid_arcconf_zabbix_lld.py "$1" "$2" "$3"
UserParameter=mscc.discover.ld,python /opt/FiMo3/raid_disk_storcli/nodefiles/script/raid_arcconf_zabbix_lld.py ld -1 lld